apiVersion: apps/v1
kind: Deployment
metadata:
  name: tsjyyy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tsjyyy
  template:
    metadata:
      labels:
        app: tsjyyy
    spec:
      containers:
      - image: okteto.dev/tsjyyy:latest
        name: tsjyyy
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "32641b10-a453-4a11-9ed0-13c8733cd610"
        - name: Vless_Path
          value: "/vl5fde55"
        - name: Vmess_UUID
          value: "32641b10-a453-4a11-9ed0-13c8733cd610"
        - name: Vmess_Path
          value: "/vm6fdf66"
        - name: Share_Path
          value: "/v2link"
